name: pulsar-detection
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.10

  # Core Data Science Stack
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0

  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0

  # Jupyter
  - jupyter>=1.0.0
  - notebook>=7.0.0
  - ipykernel>=6.25.0

  # Configuration
  - pyyaml>=6.0

  # Progress bars
  - tqdm>=4.66.0

  # Testing and Code Quality
  - pytest>=7.4.0
  - black>=23.0.0
  - flake8>=6.0.0

  # Pip dependencies (not available in conda)
  - pip
  - pip:
    - imbalanced-learn>=0.11.0
    - streamlit>=1.28.0  # For app deployment